export const FETCH_OKRS_REQUEST = "FETCH_OKRS_REQUEST";
export const FETCH_OKRS_SUCCESS = "FETCH_OKRS_SUCCESS";
export const FETCH_OKRS_ERROR = "FETCH_OKRS_ERROR";
export const SET_CATEGORY_FILTER = "SET_CATEGORY_FILTER";
